# Generated by Django 6.0.1 on 2026-03-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('season', models.CharField(max_length=20)),
                ('recommended_crop', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
