# Generated by Django 6.0.1 on 2026-03-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('soil', models.CharField(max_length=50)),
                ('nitrogen', models.IntegerField()),
                ('phosphorus', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('recommendation', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
