# Generated by Django 6.0.3 on 2026-03-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmerdata_user_fertilizerrecommendation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('rain_min', models.FloatField()),
                ('rain_max', models.FloatField()),
                ('soil', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'crop_data',
            },
        ),
    ]
