# Generated by Django 6.0.3 on 2026-03-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_cropdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=50)),
                ('base_fertilizer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fertilizer_data',
            },
        ),
    ]
